// Code generated by go-bindata.
// sources:
// bindata/bindings.json
// bindata/monsters.json
// bindata/tiles.json
// DO NOT EDIT!

package gorl

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataBindingsJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\xd3\x5d\x4f\x83\x30\x14\x06\xe0\x7b\x7e\xc5\x09\xd7\xd6\x4c\x67\xfc\xd8\x6d\x87\x73\xc9\x36\x3f\xd0\x2c\x31\xde\x94\xd1\x01\x0e\x7a\x10\x0a\x6e\x1a\xff\xbb\x29\xa6\xd4\x2d\x27\xbb\x7d\xde\xd3\x37\xed\x21\x7c\x7b\x00\x00\xfe\xa9\x3f\x02\x7f\x8c\xa0\x50\xa7\x99\x4a\xfc\x93\x3f\x46\xc3\x33\xc4\x8d\x85\xb7\x66\x30\x18\xae\x8c\xf2\x3c\x2b\x22\x68\xca\xbd\x44\xba\x24\xc6\x4f\x65\x33\xce\xba\x23\x8f\x4d\xa6\x2d\x8d\xef\x97\x0b\x63\x73\x6c\xe5\xde\xec\x2c\xb8\x7d\xee\x83\x5c\xae\xfb\x13\x4f\xd3\xc9\x9d\x4b\xaa\x2c\x49\xfb\x28\x34\x1c\x8a\x56\x5a\x78\x79\xe8\x07\xdd\x0d\x33\x63\x53\xd5\x4a\xa5\xb1\xda\x59\xfd\x38\xbc\x59\xdd\x95\x69\xa1\x6b\x2b\x5f\x46\x5e\x45\x09\x61\x29\xf3\xdc\xea\xc8\x68\xb0\xd5\x52\xc5\x32\x86\x15\x16\x85\x50\xb1\x0d\xe7\x6c\x7b\x2c\x4e\xc9\x17\xbe\x93\x0b\xd9\x10\x4f\xc9\xe9\x3d\x5c\x90\xb5\xe7\x64\xed\x35\x51\x7b\x49\xd7\x72\x16\x91\xc5\x9c\x29\xb2\x9a\xb3\x92\x28\xe7\x6c\x4d\xd7\x5f\x19\x5e\x60\xa5\x53\x58\xca\xba\xe7\x1b\xc7\x81\x70\x7c\xd6\x7d\x1e\x6c\x0e\xa6\x87\x8e\xff\x4f\xef\xe8\xee\x86\xee\x8e\xe8\x6e\x45\x77\x27\x86\x27\x95\x88\x2c\xc4\xdd\x4f\x54\x61\xe9\x7b\x3f\xde\x6f\x00\x00\x00\xff\xff\x7f\x9e\x09\x65\x59\x03\x00\x00")

func bindataBindingsJsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataBindingsJson,
		"bindata/bindings.json",
	)
}

func bindataBindingsJson() (*asset, error) {
	bytes, err := bindataBindingsJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata/bindings.json", size: 857, mode: os.FileMode(420), modTime: time.Unix(1501346228, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindataMonstersJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb4\xce\xbf\xae\x82\x30\x14\x06\xf0\x99\x3e\xc5\xc9\x99\x19\x4a\xb9\x7f\x92\x6e\xf7\x4a\x8c\x83\xba\xf8\x04\x47\x38\x2a\x01\x8a\xa9\xa0\x03\xe1\xdd\x0d\x45\x92\x06\x57\xd9\xbe\xaf\x5f\xdb\xfc\x3a\x01\x00\x80\x12\x35\x74\x22\xc0\x3d\x55\x8c\x1a\xb0\x35\x85\xa9\x1f\x06\x52\xcb\xd4\xb4\x96\x31\x14\x01\x1e\xae\x76\x87\x1a\x7e\x5f\x79\x3d\xe5\x7f\xba\x71\x42\x15\x9d\x87\xa7\x4a\x4d\x47\x7f\x2b\xd4\x10\xc9\xa1\x6e\xf2\x26\xc9\x53\x37\xbb\xbe\xe5\x3b\x97\xc3\x3a\x7e\xc5\x9c\xb9\xab\x52\x3a\x4d\x1f\x8e\xa8\x68\x86\xba\xb4\x15\x19\x5f\x12\x79\x12\xf5\x2e\x91\x1f\x93\xa8\x99\xa4\xa8\x8f\x75\x99\xf9\x94\xd8\xa3\x7c\x2d\x49\x89\x67\x94\xdc\x9c\xd8\x1a\x2a\x7d\xcc\xb7\x87\xf9\x59\x04\x23\x7a\xf1\x0c\x00\x00\xff\xff\x57\x88\xa9\x0d\x3a\x02\x00\x00")

func bindataMonstersJsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataMonstersJson,
		"bindata/monsters.json",
	)
}

func bindataMonstersJson() (*asset, error) {
	bytes, err := bindataMonstersJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata/monsters.json", size: 570, mode: os.FileMode(420), modTime: time.Unix(1501284088, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindataTilesJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xac\xd3\x4d\x6a\xc3\x30\x10\x05\xe0\xb5\x74\x8a\x41\xeb\x2c\xea\xfe\x37\x87\x28\x5d\xf4\x02\xaf\xf6\x38\x11\xc8\x23\xa3\x91\xe3\x45\xc8\xdd\x8b\x4b\x0a\xc5\x6a\x31\x88\x6e\x9f\xe0\x43\xc3\xcc\x3b\x5b\xe3\x6e\xdc\x9e\xce\xd6\x18\xf7\x8a\x81\xdd\x9e\x5c\x3e\x32\x9d\xa2\xef\xdc\x6e\x49\xdf\xa0\x8a\x8f\xb0\xbc\xf4\x08\xca\x5f\xe1\x7b\x82\xe8\x88\xc4\x92\xbf\x73\x6b\x2e\x3b\x6b\x5c\xb3\xd6\x34\x06\xdf\xd1\x8c\x10\xaa\xbc\xdb\xc2\xcb\x51\x98\xfa\x10\x63\x2a\xc0\x9c\xa6\xdf\xbc\x25\xbe\x72\x77\x6b\xee\x90\xa0\x5a\x01\xdd\xff\x17\xf4\x50\x0e\x08\x9f\x94\x02\xa3\xf3\x72\xa0\x69\xac\x40\x1f\x37\xd0\x2e\xce\x52\xc1\x3e\x15\x2c\x63\x46\xe6\x72\x13\x7f\xad\xf6\x07\xf6\xbc\xc6\xfa\xc4\x7a\xac\xe6\x5e\xd6\x5c\x8b\x13\x13\x4b\x4e\x90\x96\x2b\x86\x6d\x8a\x62\xc4\x96\x21\x54\xfd\xc3\xa6\xe8\x86\x1f\xc6\xab\x40\x43\x9c\x24\xc3\x4b\x79\x42\x5b\x2d\xb1\x17\xfb\x19\x00\x00\xff\xff\x22\xe0\x4f\x7c\xc7\x03\x00\x00")

func bindataTilesJsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataTilesJson,
		"bindata/tiles.json",
	)
}

func bindataTilesJson() (*asset, error) {
	bytes, err := bindataTilesJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata/tiles.json", size: 967, mode: os.FileMode(420), modTime: time.Unix(1501421350, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bindata/bindings.json": bindataBindingsJson,
	"bindata/monsters.json": bindataMonstersJson,
	"bindata/tiles.json": bindataTilesJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"bindata": &bintree{nil, map[string]*bintree{
		"bindings.json": &bintree{bindataBindingsJson, map[string]*bintree{}},
		"monsters.json": &bintree{bindataMonstersJson, map[string]*bintree{}},
		"tiles.json": &bintree{bindataTilesJson, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

