// Code generated by go-bindata.
// sources:
// bindata/bindings.json
// bindata/monsters.json
// bindata/tiles.json
// DO NOT EDIT!

package gorl

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataBindingsJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\xce\xcd\x4e\x84\x30\x10\xc0\xf1\x3b\x4f\x31\xe9\xd9\x35\x9b\x78\xdb\x2b\xa0\x92\x80\x5f\x68\x4c\x8c\x97\x4a\x47\x68\x2c\x1d\x84\x82\xa8\xf1\xdd\x4d\x31\x53\x82\xd9\xeb\xef\x3f\x33\x99\xef\x08\x00\x40\x9c\x8a\x03\x88\x84\xc0\x92\x6b\xb4\xad\xc5\xc9\x1f\x1b\xcf\x39\xd1\x1b\xc3\xf3\xb8\xdf\x9f\x55\x5e\x63\xa3\xdb\x17\x18\xbb\x4d\xc1\xb5\x28\xfa\xb0\xdc\xe2\xdd\xb2\x72\x3b\x6a\xc7\x94\x5c\x3f\x5e\x79\x2b\x68\xc2\xcd\x6c\x9e\x9e\xdf\x87\x60\xf0\x35\x6c\xdc\x65\x17\x97\x6b\xe9\x75\xdd\x84\x54\x7a\x2e\xe5\x84\x0c\x0f\x37\x61\x70\xfd\x50\x7b\xcb\xec\x84\xd6\x51\xff\xc9\xfa\xfe\xff\xb3\x61\x39\xe6\xa4\x1b\x58\xbe\xbc\x3c\xc9\x0e\xca\x0e\x8d\x61\x3d\x78\x4d\x67\x87\x56\xa1\x82\x8a\xda\x56\x5a\xc5\xb1\xd8\xcd\x47\x73\xf4\x13\xfd\x06\x00\x00\xff\xff\x02\xb6\xa1\xc3\x72\x01\x00\x00")

func bindataBindingsJsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataBindingsJson,
		"bindata/bindings.json",
	)
}

func bindataBindingsJson() (*asset, error) {
	bytes, err := bindataBindingsJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata/bindings.json", size: 370, mode: os.FileMode(420), modTime: time.Unix(1501331372, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindataMonstersJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb4\xce\xbf\xae\x82\x30\x14\x06\xf0\x99\x3e\xc5\xc9\x99\x19\x4a\xb9\x7f\x92\x6e\xf7\x4a\x8c\x83\xba\xf8\x04\x47\x38\x2a\x01\x8a\xa9\xa0\x03\xe1\xdd\x0d\x45\x92\x06\x57\xd9\xbe\xaf\x5f\xdb\xfc\x3a\x01\x00\x80\x12\x35\x74\x22\xc0\x3d\x55\x8c\x1a\xb0\x35\x85\xa9\x1f\x06\x52\xcb\xd4\xb4\x96\x31\x14\x01\x1e\xae\x76\x87\x1a\x7e\x5f\x79\x3d\xe5\x7f\xba\x71\x42\x15\x9d\x87\xa7\x4a\x4d\x47\x7f\x2b\xd4\x10\xc9\xa1\x6e\xf2\x26\xc9\x53\x37\xbb\xbe\xe5\x3b\x97\xc3\x3a\x7e\xc5\x9c\xb9\xab\x52\x3a\x4d\x1f\x8e\xa8\x68\x86\xba\xb4\x15\x19\x5f\x12\x79\x12\xf5\x2e\x91\x1f\x93\xa8\x99\xa4\xa8\x8f\x75\x99\xf9\x94\xd8\xa3\x7c\x2d\x49\x89\x67\x94\xdc\x9c\xd8\x1a\x2a\x7d\xcc\xb7\x87\xf9\x59\x04\x23\x7a\xf1\x0c\x00\x00\xff\xff\x57\x88\xa9\x0d\x3a\x02\x00\x00")

func bindataMonstersJsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataMonstersJson,
		"bindata/monsters.json",
	)
}

func bindataMonstersJson() (*asset, error) {
	bytes, err := bindataMonstersJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata/monsters.json", size: 570, mode: os.FileMode(420), modTime: time.Unix(1501284088, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindataTilesJson = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xac\xd1\x4b\x6a\xc4\x30\x0c\xc6\xf1\xb5\x7d\x0a\xe1\x75\x16\x7d\x3f\x72\x88\xd2\x45\x2f\xa0\xc6\x4a\x62\x70\xed\x20\x39\xc9\x22\xe4\xee\x25\xa5\x85\x62\xb7\x0c\x63\x66\xfb\x17\xfc\x40\x7c\x9b\x56\xe6\xca\xb4\xb0\x69\xa5\xcc\x0b\x7e\x90\x69\xc1\xa4\x91\x60\x89\xce\x9a\xe6\xa8\xaf\x28\x82\xef\xfe\xb8\xf4\xe8\x85\xbe\xe2\x1b\x63\x90\x09\x99\x42\xfa\xe9\x5a\xed\x8d\x56\xe6\x3a\xd7\x24\x7a\x67\x61\x45\xef\xab\xbc\x9b\xc2\x4b\x31\x10\xf4\x3e\x46\x2e\xc0\xc4\xf3\x5f\xde\x91\xbf\xb9\xdb\x9c\x1b\x18\x45\x2a\xa0\xbb\x4b\x41\xf7\xe5\x83\xe8\x58\xc0\x13\x5a\x17\x06\x98\xa7\x0a\xf4\xe1\x04\x6a\xe3\x1a\x2a\xd8\xc7\x82\x25\x5c\x31\x51\xb9\xc4\x7f\xd3\xfe\xc2\x9e\x72\xac\x67\x92\xb1\x9a\x7b\xce\xb9\x0e\x17\x02\x0a\x89\x31\x74\x74\xe6\xb3\x7a\xd7\x9f\x01\x00\x00\xff\xff\x67\x46\xa1\xe1\x1b\x03\x00\x00")

func bindataTilesJsonBytes() ([]byte, error) {
	return bindataRead(
		_bindataTilesJson,
		"bindata/tiles.json",
	)
}

func bindataTilesJson() (*asset, error) {
	bytes, err := bindataTilesJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata/tiles.json", size: 795, mode: os.FileMode(420), modTime: time.Unix(1500979352, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bindata/bindings.json": bindataBindingsJson,
	"bindata/monsters.json": bindataMonstersJson,
	"bindata/tiles.json": bindataTilesJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"bindata": &bintree{nil, map[string]*bintree{
		"bindings.json": &bintree{bindataBindingsJson, map[string]*bintree{}},
		"monsters.json": &bintree{bindataMonstersJson, map[string]*bintree{}},
		"tiles.json": &bintree{bindataTilesJson, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

