* Speeds
** Human walking speed is ~1.5m/s
** Running speed (given figures are world records, so it would be a bit below)
*** https://en.wikipedia.org/wiki/Running#Limits_of_speed
*** Flat-out sprint ~10m/s - So we might say 6*walk = 9m/s
*** Longer distances ~5m/s - 3*walk = 5m/s
* Distance scales
** Due to walking speed, dungeon cells could be 1.5m², to allow a nice easy one-second-per-turn default
*** This scale is probably enough to walk through (so corridoors make sense) but still nice and narrow.
**** Maybe very large monsters (e.g. dragons) can't fit through such narrow spaces?
***** In that case, how the hell did they get so deep into a dungeon?!
****** Perhaps there are special dungeons for this, with mixed-size corridoors.
** Overworld scales would be bigger, maybe each tile is a kilometre or half a kilometre squared?
*** Or - fitting with existing dungeon size - 150m². Since a dungeon is 100x100
**** This would make each 6 tiles 9km long
**** We could use a large scale - 100 * 150 = 15000 m = 15km
***** This scale would be the meta-overworld
***** each meta-ow tile would be 100*100 ow tiles
**** For scale, the distance between Paris and London is 460km - 30 meta-ow tiles
**** How about a Great Britain sized map?
***** Land's End → John o' Groats is ~1500 km - 100 mow tiles
***** West-Coast wales → Ipswich is ~440 km - 29 mow tiles
***** This would give 2900 mow tiles - probably not a huge amount to store…
****** …especially not if we use seeds to generate overworld tile details OwO
***** At this scale, London (~1500km², ~38km on each side if we count as a square) would be 2 tiles wide and tall
****** So a "city" would be one mow tile, and a "metropolis" would be four mow tiles
******* Perhaps a town takes up multiple overworld tiles, and a village takes up one or two
* Time scales
** As above, one second per turn. (1000 ms)
** On the overworld, the tiles are 100 times bigger, so it would be 100 seconds (100,000 ms) - roughly a minute and a half.
*** On the meta-overworld, it would be 10000 seconds (10,000,000 ms) - two hours, 46 minutes.
** Time should be stored on the milisecond-day-month-year scale, and clocked over at some high value each day.
*** 86,400,000 miliseconds = one day
**** big number, but it will fit in an int32
*** So we can have 12th of November 1234, 12345ms. Easy to convert to Terran hours and minutes.
*** This allows the player or monsters to be slowed by a factor of 1000! Unlikely to happen, but it's good to keep the option available.
**** Or, maybe have ultra-slow monsters…
** Humans should eat every day
*** You'll feel hungry after four hours of activity
*** When you go to sleep, you will be either hungry in the morning, or starving if you are hungry already.
*** Hungry is just a warning; starvation incurs stat penalties.
**** Ascetics get stat boosts during hunger and starvation
*** If you're starving for a week, you die. (since you're very active)
